FROM ubuntu:latest

RUN apt -qq update && \
	apt -qq -y install sudo

RUN groupadd -g 1001 ubuntu && \
	useradd -rm -d /home/ubuntu -s /bin/bash -g ubuntu -G sudo -u 1001 ubuntu

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN DEBIAN_FRONTEND=noninteractive TZ=Europe/Stockholm apt -qq -y install tzdata

RUN mkdir -p /home/ubuntu/.local/bin && \
	chown -R ubuntu:ubuntu /home/ubuntu && \
	chmod -R 775 /home/ubuntu

RUN echo "export PATH=\"/home/ubuntu/.local/bin:$PATH\"" >> /home/ubuntu/.bashrc

USER ubuntu

WORKDIR /home/ubuntu

ADD . /home/ubuntu/.dotfiles
