FROM ubuntu:22.04

RUN apt -qq update && \
	apt -qq -y install sudo curl wget git build-essential software-properties-common g++ cmake stow ripgrep fd-find nano unzip zip

RUN groupadd -g 1001 ubuntu && \
	useradd -rm -d /home/ubuntu -s /bin/bash -g ubuntu -G sudo -u 1001 ubuntu

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN DEBIAN_FRONTEND=noninteractive TZ=Europe/Stockholm apt -qq -y install tzdata

RUN mkdir -p /home/ubuntu/.local/bin

ADD . /home/ubuntu/.dotfiles

RUN chown -R ubuntu:ubuntu /home/ubuntu && \
	chmod -R 775 /home/ubuntu

RUN echo "export PATH=\"/home/ubuntu/.local/bin:$PATH\"" >> /home/ubuntu/.bashrc

RUN apt -qq -y install \ 
		php8.1-bcmath \
		php8.1-xml \
		php8.1-mysql \
		php8.1-zip \
		php8.1-intl \
		php8.1-ldap \
		php8.1-gd \
		php8.1-cli \
		php8.1-bz2 \
		php8.1-curl \
		php8.1-mbstring \
		php8.1-pgsql \
		php8.1-opcache \
		php8.1-soap \
		php8.1-cgi 

WORKDIR /home/ubuntu

USER ubuntu
