require('afridlund85.plugins')
require('afridlund85.colorscheme')

require('afridlund85.mason')
require('afridlund85.lsp')
require('afridlund85.cmp')
require('afridlund85.null_ls')
require('afridlund85.treesitter')
require('afridlund85.dap')
require('afridlund85.rust_tools')

require('afridlund85.telescope')
-- require('afridlund85.nerdtree')
require('afridlund85.nvim_tree')
require('afridlund85.trouble')
require('afridlund85.gitsigns')
require('afridlund85.lualine')
require('afridlund85.bufferline')
require('afridlund85.comment')
require('afridlund85.autopairs')
require('afridlund85.ts-autotag')
require('afridlund85.toggleterm')
require('afridlund85.spectre')

require('afridlund85.keymaps')
require('afridlund85.options')
