require('afridlund85.plugins')
require('afridlund85.lsp')
require('afridlund85.cmp')
require('afridlund85.treesitter')
require('afridlund85.dap')
require('afridlund85.rust_tools')

require('afridlund85.telescope')
require('afridlund85.nvim_tree')
require('afridlund85.gitsigns')
require('afridlund85.lualine')
require('afridlund85.toggleterm')

require('afridlund85.keymaps')
require('afridlund85.options')
